server:
  port: 8080
  servlet:
    context-path: /api/catalog

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/flights_catalog?autoReconnect=true"
    username: root
    password:
    validation-query: select 1;
    maxActive: 100
  jpa:
    show-sql: false
    generate-dll: false
    properties:
      hibernate:
        ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MySQL7Dialect
        hbm2ddl.auto: validate